{{- if .Values.secret.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Release.Name  }}
  labels:
    {{- include "portal-name.labels" . | nindent 4 }}
spec:
  backendType: systemManager
  {{- with .Values.secrets }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

